
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decasaemcasa_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - decasaemcasa
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: decasaemcasa_nginx
    restart: unless-stopped
    ports:
      - "8585:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - decasaemcasa
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: decasaemcasa_db
    restart: unless-stopped
    ports:
      - "3388:3306"
    environment:
      MYSQL_DATABASE: decasaemcasa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: decasaemcasa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - decasaemcasa

  mailhog:
    image: mailhog/mailhog:latest
    container_name: decasaemcasa_mailhog
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - decasaemcasa

volumes:
  dbdata:
    driver: local

networks:
  decasaemcasa:
    driver: bridge

